_format_version: "3.0"
_transform: true

services:
  - name: orders
    url: http://host.docker.internal:3300
    protocol: http
    host: host.docker.internal
    port: 3300
    connect_timeout: 30000
    retries: 5
    path: /
    routes:
      - name: api-orders
        protocols:
          - http
          - https
        paths:
          - /orders
  
  - name: invoices
    url: http://host.docker.internal:3301
    protocol: http
    host: host.docker.internal
    port: 3300
    connect_timeout: 30000
    retries: 5
    path: /
    routes:
      - name: api-invoices
        protocols:
          - http
          - https
        paths:
          - /invoices

plugins:
  - name: cors
    config:
      origins: 
        - "*"
      methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers: 
        - Accept
        - Content-Type
        - Authorization